# Generated by Django 5.0.1 on 2024-01-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
